import { useEffect, useState, type FormEvent } from 'react'
import { FiCheckCircle, FiClipboard, FiClock, FiLink, FiPlus, FiSlash, FiTruck } from 'react-icons/fi'
import { useAuth } from '../auth/useAuth'
import { ApiError } from '../services/auth-api'
import { shippingApi } from '../services/shipping-api'
import type { Carrier, CarrierInput, Pickup, PickupInput, PickupStatus } from '../types/shipping'
import '../styles/users.css'
import '../styles/shipping.css'

const labels: Record<PickupStatus, string> = { Preparing: 'Em preparação', ReadyForPickup: 'Pronto para coleta', Collected: 'Coletado', Cancelled: 'Cancelado' }

export default function ShippingPage({ initialTab = 'pickups' }: { initialTab?: 'pickups' | 'carriers' }) {
  const { session } = useAuth(); const token = session?.accessToken ?? ''; const permissions = session?.user.permissions ?? []
  const [tab, setTab] = useState(initialTab); const [carriers, setCarriers] = useState<Carrier[]>([]); const [pickups, setPickups] = useState<Pickup[]>([])
  const [carrierModal, setCarrierModal] = useState(false); const [pickupModal, setPickupModal] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const canManageCarriers = permissions.includes('carriers.manage'); const canManageDispatch = permissions.includes('dispatch.manage'); const canUpdate = permissions.includes('dispatch.readiness.update')

  function load() { Promise.all([shippingApi.carriers(token), shippingApi.pickups(token)]).then(([carrierData, pickupData]) => { setCarriers(carrierData); setPickups(pickupData); setError('') }).catch((reason: unknown) => setError(reason instanceof ApiError ? reason.message : 'Não foi possível carregar a expedição.')) }
  useEffect(load, [token])
  function success(message: string) { setNotice(message); window.setTimeout(() => setNotice(''), 3500); load() }

  async function createCarrier(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); const value: CarrierInput = { name: String(data.get('name')), taxId: String(data.get('taxId') || '') || undefined, contactName: String(data.get('contactName') || '') || undefined, email: String(data.get('email') || '') || undefined, phone: String(data.get('phone') || '') || undefined }
    try { await shippingApi.createCarrier(token, value); setCarrierModal(false); success('Transportadora cadastrada.') } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Não foi possível cadastrar.') }
  }

  async function createPickup(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); const scheduled = String(data.get('scheduledAtUtc') || ''); const value: PickupInput = { carrierId: String(data.get('carrierId')), orderReference: String(data.get('orderReference')), description: String(data.get('description') || '') || undefined, volumeCount: Number(data.get('volumeCount')), scheduledAtUtc: scheduled ? new Date(scheduled).toISOString() : undefined }
    try { await shippingApi.createPickup(token, value); setPickupModal(false); success('Solicitação de coleta criada.') } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Não foi possível criar a coleta.') }
  }

  async function updatePickup(item: Pickup, status: PickupStatus) { try { await shippingApi.setPickupStatus(token, item.id, status); success(`Coleta atualizada para ${labels[status].toLowerCase()}.`) } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Não foi possível atualizar.') } }
  async function copyLink(item: Pickup) { await navigator.clipboard.writeText(`${window.location.origin}/coleta/${item.publicAccessToken}`); setNotice('Link seguro copiado para compartilhar com a transportadora.'); window.setTimeout(() => setNotice(''), 3500) }

  return <main className="dashboard-content users-page shipping-page">
    <header className="users-heading"><div><span className="eyebrow eyebrow--blue">Logística de saída</span><h1>Transportadoras e coletas</h1><p>Evite deslocamentos desnecessários informando quando cada carga está realmente pronta.</p></div>{tab === 'pickups' && canManageDispatch ? <button className="button button--primary" onClick={() => setPickupModal(true)}><FiPlus /> Nova coleta</button> : tab === 'carriers' && canManageCarriers ? <button className="button button--primary" onClick={() => setCarrierModal(true)}><FiPlus /> Nova transportadora</button> : null}</header>
    <div className="shipping-tabs"><button className={tab === 'pickups' ? 'active' : ''} onClick={() => setTab('pickups')}><FiClipboard /> Coletas</button><button className={tab === 'carriers' ? 'active' : ''} onClick={() => setTab('carriers')}><FiTruck /> Transportadoras</button></div>
    {error && <div className="users-alert">{error}</div>}
    {tab === 'pickups' ? <section className="pickup-grid">{pickups.length === 0 ? <div className="shipping-empty"><FiTruck /><strong>Nenhuma coleta cadastrada</strong><span>Cadastre uma transportadora e crie a primeira solicitação.</span></div> : pickups.map((item) => <article className="pickup-card" key={item.id}><header><div><small>{item.code}</small><h2>{item.orderReference}</h2></div><span className={`pickup-status pickup-status--${item.status}`}>{labels[item.status]}</span></header><dl><div><dt>Transportadora</dt><dd>{item.carrierName}</dd></div><div><dt>Volumes</dt><dd>{item.volumeCount}</dd></div><div><dt>Previsão</dt><dd>{item.scheduledAtUtc ? new Date(item.scheduledAtUtc).toLocaleString('pt-BR') : 'A confirmar'}</dd></div></dl><p>{item.description ?? 'Sem observações adicionais.'}</p><footer><button title="Copiar link da transportadora" onClick={() => copyLink(item)}><FiLink /> Copiar link</button>{canUpdate && item.status === 'Preparing' && <button className="ready" onClick={() => updatePickup(item, 'ReadyForPickup')}><FiCheckCircle /> Marcar pronta</button>}{canUpdate && item.status === 'ReadyForPickup' && <button className="ready" onClick={() => updatePickup(item, 'Collected')}><FiTruck /> Confirmar coleta</button>}{canUpdate && (item.status === 'Preparing' || item.status === 'ReadyForPickup') && <button className="cancel" title="Cancelar coleta" onClick={() => updatePickup(item, 'Cancelled')}><FiSlash /></button>}</footer></article>)}</section> : <section className="users-panel"><div className="users-table-wrap"><table className="users-table"><thead><tr><th>Transportadora</th><th>Documento</th><th>Contato</th><th>Status</th><th>Ações</th></tr></thead><tbody>{carriers.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.taxId ?? 'Não informado'}</td><td>{item.email ?? item.phone ?? item.contactName ?? 'Não informado'}</td><td><span className={`user-status ${item.isActive ? 'user-status--active' : 'user-status--inactive'}`}><span />{item.isActive ? 'Ativa' : 'Inativa'}</span></td><td>{canManageCarriers && <button className="icon-action" onClick={async () => { await shippingApi.setCarrierStatus(token, item.id, !item.isActive); success(item.isActive ? 'Transportadora inativada.' : 'Transportadora reativada.') }}>{item.isActive ? <FiSlash /> : <FiCheckCircle />}</button>}</td></tr>)}</tbody></table></div></section>}
    {carrierModal && <div className="modal-backdrop"><section className="user-modal shipping-modal"><header className="user-modal__header"><span className="user-modal__icon"><FiTruck /></span><div><span className="panel__eyebrow">Parceiro logístico</span><h2>Cadastrar transportadora</h2></div></header><form onSubmit={createCarrier}><div className="user-modal__body form-grid"><label className="modal-field modal-field--full"><span>Nome da transportadora</span><input name="name" required autoFocus /></label><label className="modal-field"><span>CNPJ (opcional)</span><input name="taxId" /></label><label className="modal-field"><span>Contato</span><input name="contactName" /></label><label className="modal-field"><span>E-mail</span><input name="email" type="email" /></label><label className="modal-field"><span>Telefone</span><input name="phone" /></label></div><footer className="user-modal__footer"><button className="button button--secondary" type="button" onClick={() => setCarrierModal(false)}>Cancelar</button><button className="button button--primary">Cadastrar</button></footer></form></section></div>}
    {pickupModal && <div className="modal-backdrop"><section className="user-modal shipping-modal"><header className="user-modal__header"><span className="user-modal__icon"><FiClock /></span><div><span className="panel__eyebrow">Programação de saída</span><h2>Nova solicitação de coleta</h2></div></header><form onSubmit={createPickup}><div className="user-modal__body form-grid"><label className="modal-field modal-field--full"><span>Transportadora</span><select name="carrierId" required>{carriers.filter((item) => item.isActive).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="modal-field"><span>Pedido / referência</span><input name="orderReference" required /></label><label className="modal-field"><span>Volumes</span><input name="volumeCount" type="number" min="1" defaultValue="1" required /></label><label className="modal-field modal-field--full"><span>Previsão da coleta</span><input name="scheduledAtUtc" type="datetime-local" /></label><label className="modal-field modal-field--full"><span>Descrição da carga</span><textarea name="description" rows={3} /></label></div><footer className="user-modal__footer"><button className="button button--secondary" type="button" onClick={() => setPickupModal(false)}>Cancelar</button><button className="button button--primary" disabled={!carriers.some((item) => item.isActive)}>Criar coleta</button></footer></form></section></div>}
    {notice && <div className="success-toast"><FiCheckCircle /> {notice}</div>}
  </main>
}
